#!name = DONG SYSTEM
#!desc = Clean Ads + Privacy + Stable
#!author = DONGDAREALEST
#!homepage = https://github.com/Dongdarealest
#!icon = https://raw.githubusercontent.com/Dongdarealest/DONGUNLOCK/main/premium.png

[General]
bypass-system = true
skip-proxy = *.local, localhost, 192.168.0.0/16

[Rule]
# Apple & system
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT

# Ads phổ biến
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,googlesyndication.com,REJECT
DOMAIN-SUFFIX,ads.youtube.com,REJECT

# Tracking
DOMAIN-SUFFIX,app-measurement.com,REJECT
DOMAIN-SUFFIX,google-analytics.com,REJECT

FINAL,DIRECT
